title: Lillendandie | Artist & Illustrator

# Site settings
name: Lillendandie
description: "Artist & Illustrator"
url: ""

# Build settings
markdown: kramdown
permalink: pretty

#Redirect
theme: jekyll-theme-cayman