# Site settings
title: Lillendandie Art
email: dandie.illustration@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Synthia Lillendandie Art Portfolio
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: lillendandie
github_username:  lillendandie

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: false
    permalink: /portfolio/:path/
 


